# refer from https://squidfunk.github.io/mkdocs-material/
site_name: Memorandum
site_description: Memorandum 
site_author: cunfus
site_url: https://cunfus.github.io/memorandum

# repo_name: 'cunfus/memorandum'
# repo_url: https://github.com/cunfus/memorandum

copyright: Copyright &copy; 2024 <a href="https://github.com/cunfus" target="_blank" rel="noopener">cunfus</a>



theme:
  name: material
  language: zh
  custom_dir: overrides
  # logo:  asserts/images/logo.png
  favicon: asserts/images/code-solid.svg
  palette:
    - scheme: custom
      # primary: orange
      accent: orange
      toggle:
        icon: material/lightbulb
        name: dark mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: eye-protection mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: light mode
  font:  
    text: 'LXGW WenKai Screen'
    code: 'Fira Code' 
  features:
    - navigation.instant     # 即时加载
    - navigation.tracking    # 锚点跟踪
    - navigation.indexes     # 次级索引页
    - navigation.tabs        # 导航选项卡
    - navigation.top         # 一键返回顶部
    - navigation.footer      # 上下页链接
    ### 代码
    - content.code.copy
    - content.code.annotate

extra_css:
  # - https://cdn.staticfile.org/lxgw-wenkai-webfont/1.6.0/style.css
  # - https://cdn.staticfile.org/lxgw-wenkai-screen-webfont/1.6.0/style.css
  - https://cdn.jsdelivr.net/npm/lxgw-wenkai-screen-webfont@1.7.0/style.css
  - stylesheets/extra.css

extra_javascript:
  - javascripts/english.js

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/cunfus
    - icon: fontawesome/solid/envelope
      link: mailto:<cunfuss@outlook.com>

plugins:
  - git-revision-date-localized:
      type: datetime
      locale: zh
      timezone: Asia/Shanghai

markdown_extensions:
  ### refer from https://shafish.cn/blog/mkdocs
  ### 术语
  - abbr            
  - pymdownx.snippets
  ### 提示
  - admonition           
  - pymdownx.details     
  - pymdownx.superfences 
  ### 按钮
  - attr_list
  ### 代码块
  - pymdownx.highlight:  
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  ### 内容标签栏
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  ### 表格
  - tables
  ### 格式化
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  ###图标
  - pymdownx.emoji:
      #emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      #emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  ### 图片
  - attr_list
  - md_in_html
  ### 列表
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

### 内容列表
nav:
  - 首页: 
    - index.md
  - 工程赏析:
    - proj/index.md
  - 领域单词:
    - domain/index.md
    - domain/elementary-mathematics.md
    - domain/advanced-mathematics.md
    - 音视频:
      - domain/audio/index.md
  - 英语:
    - english/index.md
  - 书籍:
    - book/index.md
    - 如何设计程序:
      - book/htdp/index.md
      - book/htdp/htdp-2.md
      - book/htdp/htdp-3.md
    - 计算机程序的构造和解释:
      - book/sicp/index.md
      - book/sicp/sicp-1.1.md
      - book/sicp/sicp-1.2.md
    - 数据结构和算法 in Python:
      - book/algo/index.md
  - 课程:
    - course/index.md
    - 斯坦福食品与健康导论:
      - course/food-and-health/index.md
      - course/food-and-health/metabolism.md
      - course/food-and-health/glycemic-index.md
    - 生命体征:
      - course/vital-signs/index.md
      - course/vital-signs/heart.md
    - 寻找你的专业声音:
      - course/finding-your-professional-voice/index.md
  - 编程语言:
    - codelang/index.md
    - Python:
      - codelang/python/index.md
      - codelang/python/1.md
      - codelang/python/2.md
      - codelang/python/3.md
      - codelang/python/4.md
      - codelang/python/5.md
      - codelang/python/6.md
      - codelang/python/7.md
      - codelang/python/8.md
    - C:
      - codelang/c/index.md
      - codelang/c/1.md
      - codelang/c/2.md
      - codelang/c/3.md
      - codelang/c/4.md
      - codelang/c/5.md
      - codelang/c/6.md
      - 标准库:
        - codelang/c/stl/index.md
        - codelang/c/stl/cpy.md
  - 工具:
    - tool/index.md
    - tool/man.md
    - tool/zsh.md
    - tool/tmux.md
    - tool/vim.md
    - tool/git.md
    - tool/makefile.md
    - tool/pacman.md
    - tool/markdown.md
    - tool/jupyter.md 
    - tool/manim.md 

