# refer from https://squidfunk.github.io/mkdocs-material/
site_name: 札记
site_description: 札记 
site_author: cunfus
site_url: https://cunfus.github.io/memorandum

# repo_name: 'cunfus/memorandum'
# repo_url: https://github.com/cunfus/memorandum

# copyright: Copyright &copy; 2024 <a href="https://github.com/cunfus" target="_blank" rel="noopener">cunfus</a>



theme:
  name: material
  language: zh
  custom_dir: overrides
  # logo:  asserts/images/logo.png
  favicon: asserts/images/code-solid.svg

  font:  
    text: 'LXGW WenKai Screen'
    code: 'Fira Code' 
  features:
    - navigation.instant     # 即时加载
    - navigation.tracking    # 锚点跟踪
    - navigation.indexes     # 次级索引页
    - navigation.tabs        # 导航选项卡
    - navigation.top         # 一键返回顶部
    - navigation.footer      # 上下页链接
    ### 代码
    - content.code.copy
    - content.code.annotate

extra_css:
  # - https://cdn.staticfile.org/lxgw-wenkai-webfont/1.6.0/style.css
  # - https://cdn.staticfile.org/lxgw-wenkai-screen-webfont/1.6.0/style.css
  - https://cdn.jsdelivr.net/npm/lxgw-wenkai-screen-webfont@1.7.0/style.css
  - stylesheets/extra.css

extra_javascript:
  - javascripts/english.js

# extra:
#   social:
#     - icon: fontawesome/brands/github
#       link: https://github.com/cunfus
#     - icon: fontawesome/solid/envelope
#       link: mailto:<cunfuss@outlook.com>

markdown_extensions:
  ### refer from https://shafish.cn/blog/mkdocs
  ### 术语
  - abbr            
  - pymdownx.snippets
  ### 提示
  - admonition           
  - pymdownx.details     
  - pymdownx.superfences 
  ### 按钮
  - attr_list
  ### 代码块
  - pymdownx.highlight:  
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  ### 内容标签栏
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  ### 表格
  - tables
  ### 格式化
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  ###图标
  - pymdownx.emoji:
      #emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      #emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  ### 图片
  - attr_list
  - md_in_html
  ### 列表
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

### 内容列表
nav:
  - 首页: 
    - index.md

  - 英语:
    - english/index.md
    - 词汇:
      - english/vocabulary/index.md
      - english/vocabulary/1.md

  - 课程:
    - course/index.md
    - 斯坦福食品与健康导论:
      - course/food-and-health/index.md
      - course/food-and-health/metabolism.md
      - course/food-and-health/glycemic-index.md
